name: chat_ui
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  diffutil_dart: ^4.0.0
  flutter:
    sdk: flutter
  flutter_parsed_text: ^2.2.1
  intl: ">=0.17.0 <1.0.0"
  meta: ">=1.8.0 <2.0.0"
  photo_view: ^0.14.0
  scroll_to_index: ^3.0.1
  url_launcher: ^6.1.12
  visibility_detector: ^0.4.0+2
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  flutter_linkify: ^6.0.0
  html: ^0.15.4
  linkify: ^5.0.0
  http: ">=0.13.6 <2.0.0"

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/chat_ui/assets/icon-arrow.png
    - packages/chat_ui/assets/icon-attachment.png
    - packages/chat_ui/assets/icon-delivered.png
    - packages/chat_ui/assets/icon-document.png
    - packages/chat_ui/assets/icon-error.png
    - packages/chat_ui/assets/icon-seen.png
    - packages/chat_ui/assets/icon-send.png
    - packages/chat_ui/assets/2.0x/icon-arrow.png
    - packages/chat_ui/assets/2.0x/icon-attachment.png
    - packages/chat_ui/assets/2.0x/icon-delivered.png
    - packages/chat_ui/assets/2.0x/icon-document.png
    - packages/chat_ui/assets/2.0x/icon-error.png
    - packages/chat_ui/assets/2.0x/icon-seen.png
    - packages/chat_ui/assets/2.0x/icon-send.png
    - packages/chat_ui/assets/3.0x/icon-arrow.png
    - packages/chat_ui/assets/3.0x/icon-attachment.png
    - packages/chat_ui/assets/3.0x/icon-delivered.png
    - packages/chat_ui/assets/3.0x/icon-document.png
    - packages/chat_ui/assets/3.0x/icon-error.png
    - packages/chat_ui/assets/3.0x/icon-seen.png
    - packages/chat_ui/assets/3.0x/icon-send.png
    - packages/chat_ui/assets/hi.gif
