name: chat_ex
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  chat_ui:
    path: ../
  cupertino_icons: ^1.0.2
  file_picker: ^5.3.2
  flutter:
    sdk: flutter
  http: ">=0.13.6 <2.0.0"
  image_picker: ^1.0.0
  intl: ^0.18.1
  mime: ^1.0.4
  open_filex: ^4.3.2
  path_provider: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
